version: '3'
services:
    localstack:
        image: localstack/localstack
        ports:
            - '4566:4566'
        environment:
            - SERVICES=dynamodb
            - PERSISTENCE=1
        networks:
            - surreal-network
        volumes:
            - localstack-data:/var/lib/localstack

    surreal:
        build:
            context: .
            dockerfile: infrastructure/Dockerfile
        ports:
            - '8000:8000'
        environment:
            - SURREAL_PATH=dynamodb://surrealdb
            - SURREAL_USER=root
            - SURREAL_PASS=pass
            - DYNAMODB_ENDPOINT=http://localstack:4566
            - AWS_DEFAULT_REGION=eu-central-1
            - AWS_ACCESS_KEY_ID=AKIAQVW33BUA5OHTH2RV
            - AWS_SECRET_ACCESS_KEY=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
        command: ["start"]
        networks:
            - surreal-network

networks:
    surreal-network:

volumes:
    localstack-data:
